version: "3"
services:
  dev-db:
    image: "mysql:5.7.10"
    container_name: dev-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-admin}"
      MYSQL_USER: "${MYSQL_USERNAME:-dev}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-dev}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-dev}"
  test-db:
    image: "mysql:5.7.10"
    container_name: test-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-admin}"
      MYSQL_USER: "${MYSQL_USERNAME:-test}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-test}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-test}"
  # cas-app:
  #   image: cas:backend
  #   container_name: cas-mono-server
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - MYSQL_CONNECT_URL=http://cas:cas@cas-db:3306/cas
  #       - CLOUDINARY_CLOUD_NAME=cas-dev-cloud-storage
  #       - CLOUDINARY_API_KEY=598799362394336
  #       - CLOUDINARY_API_SECRET=eLVBqEN5OCPzy7irOurtqDWYZ8c
  #       - PORT=8000
  #       # - WAIT_HOSTS=cas-db:3306
  #   volumes:
  #     - ./src:/app/src
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - cas-db
          
    
      
  